In [1]:
import json

import pandas as pd
import ast
import os

from typing import Union, List

# Load Impact DF

In [2]:
def try_literal_eval(x):
    if isinstance(x, str):
        x = x.strip()
        if (x.startswith("[") and x.endswith("]")) or \
           (x.startswith("{") and x.endswith("}")) or \
           (x.startswith("(") and x.endswith(")")):
            try:
                return ast.literal_eval(x)
            except (ValueError, SyntaxError):
                return x
    return x

In [3]:
dataset_dir = "/home/yishin/keith/patent_research/model_io"

In [4]:
Keyword_df = pd.read_csv(os.path.join(dataset_dir, "Impact_Sub_KW.csv"), encoding="utf-8")
# Keyword_df = Keyword_df.map(try_literal_eval)

Keyword_df.head()

,title,caption,image_paths,best_fig_desc,Loc_class,main_class,sub_class,keywords
0,Cupcake with contrasting icing,The image is a black and white picture of a cu...,['impact_dataset/2022/USD0957089-20220712/USD0...,{'FIG. 1': 'FIG. 1 is a perspective view of a ...,"{'11-01', '01-01'}",1,1,"['cupcake', 'icing']"
1,Ring with an integrated spoon,The image is a drawing of a ring with an integ...,['impact_dataset/2022/USD0966130-20221011/USD0...,{'FIG. 1': 'FIG. 1 is a front perspective view...,"{'11-01', '01-01'}",1,1,"['ring', 'spoon', 'finger']"
2,Butter stick,The image is a white and black drawing of a bu...,['impact_dataset/2022/USD0962586-20220906/USD0...,"{'FIG. 1': 'FIG. 1 is a front, top and left si...","{'01-06', '11-01'}",1,6,['butter stick']
3,Necklace,"The image is a round shape, and the necklace i...",['impact_dataset/2022/USD0962109-20220830/USD0...,{'FIG. 3': 'FIG. 3 is a right side perspective...,"{'11-01', '01-01'}",1,1,"['chain', 'pendant', 'clasp']"
4,Dietary supplement,"The image is circular in shape, and it represe...",['impact_dataset/2022/USD0941457-20220118/USD0...,{'FIG. 1': 'FIG. 1 is a top perspective view o...,"{'11-01', '01-01'}",1,1,"['circle', 'pill', 'label', 'caplet']"

In [5]:
Crops_df = pd.read_csv(os.path.join(dataset_dir, "Impact_Sub_Crops.csv"), encoding="utf-8")
# Crops_df = Crops_df.map(try_literal_eval)

Crops_df.head()

,title,caption,image_paths,best_fig_desc,Loc_class,main_class,sub_class,crop_paths
0,Cupcake with contrasting icing,The image is a black and white picture of a cu...,['impact_dataset/2022/USD0957089-20220712/USD0...,{'FIG. 1': 'FIG. 1 is a perspective view of a ...,"{'11-01', '01-01'}",1,1,['figure_crops/0_Cupcake with contrasting icin...
1,Ring with an integrated spoon,The image is a drawing of a ring with an integ...,['impact_dataset/2022/USD0966130-20221011/USD0...,{'FIG. 1': 'FIG. 1 is a front perspective view...,"{'11-01', '01-01'}",1,1,['figure_crops/1_Ring with an integrated spoon...
2,Butter stick,The image is a white and black drawing of a bu...,['impact_dataset/2022/USD0962586-20220906/USD0...,"{'FIG. 1': 'FIG. 1 is a front, top and left si...","{'11-01', '01-06'}",1,6,"['figure_crops/2_Butter stick/FIG_1.jpg', 'fig..."
3,Necklace,"The image is a round shape, and the necklace i...",['impact_dataset/2022/USD0962109-20220830/USD0...,{'FIG. 3': 'FIG. 3 is a right side perspective...,"{'11-01', '01-01'}",1,1,[]
4,Dietary supplement,"The image is circular in shape, and it represe...",['impact_dataset/2022/USD0941457-20220118/USD0...,{'FIG. 1': 'FIG. 1 is a top perspective view o...,"{'11-01', '01-01'}",1,1,['figure_crops/4_Dietary supplement/FIG_1.jpg'...

In [7]:
Keyword_df = Keyword_df.copy()
Crops_df = Crops_df.copy()

Keyword_df["original_order"] = range(len(Keyword_df))

In [10]:
Merged_df = pd.merge(
    Keyword_df,
    Crops_df,
    on=[
        "title",
        "caption",
        "image_paths",
        "best_fig_desc",
        "Loc_class",
        "main_class",
        "sub_class",
    ],
    how="outer",
    suffixes=("_keyword", "_crops")
)

In [11]:
Merged_df = Merged_df.map(try_literal_eval)

Merged_df.head()

,title,caption,image_paths,best_fig_desc,Loc_class,main_class,sub_class,keywords,original_order,crop_paths
0,3D flower-shaped throw pillow,The image is a black and white drawing of a 3D...,[impact_dataset/2022/USD0954470-20220614/USD09...,{'FIG. 1': 'FIG. 1 is a front and top perspect...,{06-13},6,13,"[pillow, flower, stem, leaves]",342.0,[figure_crops/342_3D flower-shaped throw pillo...
1,3D printer extruder,The image is a black and white drawing of a 3D...,[impact_dataset/2022/USD0955471-20220621/USD09...,{'FIG. 1': 'FIG. 1 is a perspective view of a ...,{18-02},18,2,"[barrel, nozzle, element, heater]",2078.0,[figure_crops/2078_3D printer extruder/FIG_4.j...
2,3D wall panel,The image is a black and white geometric shape...,[impact_dataset/2022/USD0947417-20220329/USD09...,{'FIG. 1': 'FIG. 1 is a front and top elevatio...,{25-01},25,1,"[panel, shape, surface, room, design, element,...",2787.0,[figure_crops/2787_3D wall panel/FIG_3.jpg]
3,Absorber for a loudspeaker,"The image shows a round shape, which is a comm...",[impact_dataset/2022/USD0940115-20220104/USD09...,{'FIG. 2': 'FIG. 2 is a bottom perspective vie...,{14-01},14,1,"[round shape, material, absorber, loudspeaker]",1531.0,[figure_crops/1531_Absorber for a loudspeaker/...
4,Abutment holder for dental implants,The image is a black and white drawing of an A...,[impact_dataset/2022/USD0967427-20221018/USD09...,{'FIG. 1': 'FIG. 1 is a perspective view of an...,{24-03},24,3,"[cylinder, holder, abutment, grip, arm, base]",2749.0,[figure_crops/2749_Abutment holder for dental ...

In [12]:
Merged_df.to_csv(
    os.path.join(dataset_dir, "Impact_Sub_Complete.csv"),
    index=False
)