In [1]:
import ast
import pandas as pd

In [2]:
def try_literal_eval(x):
    if isinstance(x, str):
        x = x.strip()
        if (x.startswith("[") and x.endswith("]")) or \
           (x.startswith("{") and x.endswith("}")) or \
           (x.startswith("(") and x.endswith(")")):
            try:
                return ast.literal_eval(x)
            except (ValueError, SyntaxError):
                return x
    return x

# Captions

In [17]:
sub_df = pd.read_csv("/home/yishin/keith/patent_research/model_io/Impact_2022_Sub_KW.csv", encoding="utf-8")
sub_df = sub_df.map(try_literal_eval)

sub_df.head()

,title,file_names,Loc_class,main_class,sub_class,llava_output,components,caption
0,Article of footwear,[impact_dataset/2022/USD0943877-20220222/USD09...,{02-04},2,4,The image you've provided appears to be a tech...,"sole, heel, toe, upper, tongue, laces, eyelets",The image is a white outline of a skateboard. ...
1,Shoe,[impact_dataset/2022/USD0950931-20220510/USD09...,{02-04},2,4,"The image shows a pair of shoes, and I will de...","sole, heel, upper, tongue, laces, eyelets","The image is a white outline of a shoe, which ..."
2,Rear combination lamp for automobile,[impact_dataset/2022/USD0957706-20220712/USD09...,"{26-06, 02-07}",2,7,The image you've provided appears to be a gray...,"base, housing, lens, switch, cord, bulb, refle...",The image is a close-up of a rear combination ...
3,Portable light beacon,[impact_dataset/2022/USD0959716-20220802/USD09...,"{02-07, 26-02}",2,7,The image you've provided appears to be a tech...,"base, stem, head, lens, switch, battery compar...",The image is a top view of a Portable light be...
4,Water shoe,[impact_dataset/2022/USD0960535-20220816/USD09...,{02-04},2,4,The image you've provided appears to be a line...,"sole, upper, tongue, laces, heel, toe cap","The image is a drawing of a water shoe, which ..."

In [18]:
for i in sub_df.head()["caption"]:
    print(i)

The image is a white outline of a skateboard. The skateboard is designed to provide a platform for skateboarding, allowing the rider to glide on various surfaces, perform tricks, and enjoy the sport.
The image is a white outline of a shoe, which is a representation of a shoe's shape and structure. Shoes are designed to protect and cushion the feet while providing support and stability during various activities such as walking, running, or playing sports. They come in different styles, materials, and sizes to accommodate the needs and preferences of individuals.
The image is a close-up of a rear combination lamp for an automobile. The shape of the image is a curved, elongated form that resembles the back of a car.

The functionality of a rear combination lamp is to provide illumination for the rear of the vehicle, making it visible to other drivers and pedestrians. These lamps are essential for safety, as they help to prevent accidents by ensuring that the vehicle is easily seen in low-light conditions or at night. Rear combination lamps typically consist of both a brake light and a tail light, which serve different purposes. The brake light indicates when the vehicle is slowing down or stopping, while the tail light provides a continuous illumination that helps to identify the vehicle's position on the road.
The image is a top view of a Portable light beacon, which is a small, handheld device designed to provide illumination in various situations. It is particularly useful for outdoor activities, such as camping, hiking, or during power outages. The light beacon is shaped like a small bowl, with a hole in the center where the light source is housed. The design allows for easy handling and efficient distribution of light.
The image is a drawing of a water shoe, which is a type of shoe designed to be worn in water. The shoe is shaped like a crocodile, with a mouth and teeth drawn on it. The functionality of a water shoe is to provide protection and support for the wearer's feet while walking or playing in water, such as in a pool, lake, or beach. The water shoe helps prevent slipping and keeps the feet dry and comfortable in wet conditions.

# Check Current Dataset

In [5]:
A = "/home/yishin/keith/patent_research/model_io/keyword_method/Impact_2022_Sub_LLaVa_KW_Triples_2.csv"

B = "/home/yishin/keith/patent_research/model_io/no_keyword_method/Impact_2022_Sub_LLaVa_NoKW_Triples_2.csv"

In [6]:
df_A = pd.read_csv(A, encoding="utf-8")
df_A = df_A.map(try_literal_eval)

df_A.head()

,title,file_names,Loc_class,main_class,sub_class,llava_output,components,Qwen
0,Article of footwear,[impact_dataset/2022/USD0943877-20220222/USD09...,{02-04},2,4,The design patent image presents a detailed te...,"sole, heel, toe, upper, tongue, laces, eyelets","[(sole, material, unknown), (sole, shape, text..."
1,Shoe,[impact_dataset/2022/USD0950931-20220510/USD09...,{02-04},2,4,"The image presents a design patent of a shoe, ...","sole, heel, upper, tongue, laces, eyelets","[(shoe, shape, broad and flat), (shoe, texture..."
2,Rear combination lamp for automobile,[impact_dataset/2022/USD0957706-20220712/USD09...,"{26-06, 02-07}",2,7,The image presents a design patent for a rear ...,"base, housing, lens, switch, cord, bulb, refle...","[(lamp, shape, flat, elongated rectangle), (la..."
3,Portable light beacon,[impact_dataset/2022/USD0959716-20220802/USD09...,"{02-07, 26-02}",2,7,The design patent image presents a portable li...,"base, stem, head, lens, switch, battery compar...","[(base, shape, flat, circular), (base, materia..."
4,Water shoe,[impact_dataset/2022/USD0960535-20220816/USD09...,{02-04},2,4,The image presents a technical drawing of a wa...,"sole, upper, tongue, laces, heel, toe cap","[(water shoe, shape, wide and flat), (water sh..."

In [7]:
df_B = pd.read_csv(B, encoding="utf-8")
df_B = df_B.map(try_literal_eval)

df_B.head()

,title,file_names,Loc_class,main_class,sub_class,llava_output,components,Qwen
0,Article of footwear,[impact_dataset/2022/USD0943877-20220222/USD09...,{02-04},2,4,The image depicts a design patent of an articl...,"sole, heel, toe, upper, tongue, laces, eyelets","[(shoe, shape, rounded toe), (shoe, shape, poi..."
1,Shoe,[impact_dataset/2022/USD0950931-20220510/USD09...,{02-04},2,4,The image presents a design patent of a single...,"sole, heel, upper, tongue, laces, eyelets","[(shoe, shape, streamlined), (shoe, material, ..."
2,Rear combination lamp for automobile,[impact_dataset/2022/USD0957706-20220712/USD09...,"{26-06, 02-07}",2,7,The image depicts a rear combination lamp for ...,"base, housing, lens, switch, cord, bulb, refle...","[(lamp, shape, curved, elongated body), (lamp,..."
3,Portable light beacon,[impact_dataset/2022/USD0959716-20220802/USD09...,"{02-07, 26-02}",2,7,The image presents a design patent for a porta...,"base, stem, head, lens, switch, battery compar...","[(beacon, shape, oval), (beacon, material, mon..."
4,Water shoe,[impact_dataset/2022/USD0960535-20220816/USD09...,{02-04},2,4,The image presents a design patent drawing of ...,"sole, upper, tongue, laces, heel, toe cap","[(water shoe, shape, elongated toe tapering to..."

## Check LLaVa Output

In [21]:
for i in df_A.head()["llava_output"]:
    print(i)

The design patent image presents a detailed technical drawing of an article of footwear, specifically a shoe. The shoe features a prominent sole with a textured surface, suggesting a grip-enhancing pattern. The sole is connected to the upper part of the shoe by a series of vertical lines, indicating a stitching detail. The upper part of the shoe is characterized by a smooth, curved shape with a slightly raised edge, possibly for a snug fit. The heel of the shoe is not visible in the image, but the sole's design implies a moderate height. The toe of the shoe is rounded and appears to be slightly protruding, which is typical for casual footwear. The tongue of the shoe is not visible, but the laces are clearly depicted. The laces are threaded through eyelets, which are evenly spaced along the top of the shoe's upper. The eyelets are small and circular, and they are evenly spaced, allowing for a consistent lacing pattern. The overall design of the shoe suggests a casual style with a focus on comfort and ease of wear.
The image presents a design patent of a shoe, captured in a technical drawing style. The shoe is depicted in a side view, allowing for a clear examination of its various components. The sole of the shoe is broad and flat, with a textured pattern that suggests grip. The heel of the shoe is raised, providing a contrast to the flat sole. The upper part of the shoe is characterized by a series of vertical lines that run along its length, adding a sense of structure and design. The tongue of the shoe is visible, extending from the top of the shoe to the sole, and it appears to be a solid piece without any visible laces or eyelets. The overall shape of the shoe is rounded, with a smooth transition from the sole to the upper. The image does not provide any additional details about the color or material of the shoe.
The image presents a design patent for a rear combination lamp for an automobile. The lamp is depicted in a three-dimensional view against a white background. The lamp's base is a flat, elongated rectangle with a series of parallel ridges along its length, providing a textured surface. The housing of the lamp is cylindrical with a tapered end, and it appears to be made of a dark, possibly metallic material. A lens is affixed to the front of the housing, which is likely designed to focus and direct the light emitted by the lamp. The switch is located on the side of the housing, near the top, and it is a small, rectangular protrusion. A cord extends from the switch, suggesting the lamp is electrically powered. The bulb is not visible in the image, but its presence is implied by the cord and switch. A reflector is positioned behind the lamp, enhancing the light's output. The bracket, which is not explicitly labeled, is a horizontal bar that connects the lamp to the vehicle, and it is located at the bottom of the lamp, extending outward from the base. The overall design of the lamp is sleek and modern, with a focus on functionality and aesthetics.
The design patent image presents a portable light beacon, which is depicted in a technical drawing style. The beacon is composed of a base, stem, head, lens, switch, and battery compartment. The base appears to be a flat, circular shape with a slightly raised edge, providing stability for the device. The stem, which connects the base to the head, is cylindrical and has a series of ridges along its length, likely for grip or aesthetic purposes. The head of the beacon is the most prominent part, featuring a large, rounded lens that is designed to focus and direct the light. The lens is centrally located on the head, and its shape suggests it is designed to emit a wide, even beam of light. To the right of the lens, there is a switch, which is a small, rectangular button with a raised edge, presumably for turning the light on and off. The battery compartment is located on the left side of the head, and it is a rectangular shape with a slightly raised edge, indicating a secure place for batteries to be inserted. The overall design of the beacon suggests a compact, portable device that is easy to use and durable.
The image presents a technical drawing of a water shoe, which is designed to resemble an alligator. The shoe's sole is wide and flat, with a textured pattern that mimics the appearance of an alligator's skin. The upper part of the shoe features a large, exaggerated eye and mouth, giving it a playful and cartoonish look. The tongue of the shoe is long and extends outward, with a small loop at the end, likely for pulling the shoe on. The laces are long and thin, threaded through eyelets on the upper part of the shoe. The heel of the shoe is small and rounded, while the toe cap is pointed and sharp, resembling the alligator's teeth. The overall design is whimsical and fun, with a clear emphasis on the alligator theme.

In [22]:
for i in df_B.head()["llava_output"]:
    print(i)

The image depicts a design patent of an article of footwear, specifically a shoe. The shoe has a distinctive overall shape with a rounded toe and a pointed toe on the opposite side. The structure of the shoe is characterized by a combination of straight and curved lines, with a prominent vertical line running down the center of the sole. The visible components include a sole with a textured pattern, a midsole, and an upper part with a series of horizontal lines and a textured pattern on the side. The proportions of the shoe are such that the sole appears to be relatively thick, the midsole is narrower, and the upper part is the most slender. Notable visual characteristics include the contrast between the smooth texture of the midsole and the rougher texture of the sole, as well as the alignment of the horizontal lines on the upper part of the shoe.
The image presents a design patent of a single shoe, depicted in a side view. The shoe exhibits a sleek, modern design with a predominantly white color scheme. The upper part of the shoe features a smooth, seamless construction with a slightly curved toe and a rounded heel. The midsole is thick and appears to be a solid, opaque material, while the outsole is not fully visible but seems to be a darker shade, possibly indicating a different material or color. The shoe's design includes a prominent, vertical, textured strip on the side, which adds a dynamic visual element to the otherwise minimalist aesthetic. The overall shape of the shoe is streamlined, with a tapered toe and a slightly wider heel, suggesting a comfortable fit and a stylish appearance.
The image depicts a rear combination lamp for an automobile, which is a crucial safety component designed to enhance visibility during nighttime driving. The lamp has a sleek, aerodynamic shape with a curved, elongated body that tapers towards the rear of the vehicle. The structure of the lamp is composed of multiple layers, with a central, elongated light-emitting diode (LED) panel that is encased within a protective, translucent cover. This cover is designed to diffuse the light evenly and prevent glare, ensuring optimal visibility for other road users. The lamp is mounted on the rear of the vehicle, typically on the trunk or the rear door, and is secured with a series of mounting points and fasteners. The overall design of the lamp is both functional and aesthetically pleasing, with a modern, streamlined appearance that complements the vehicle's design.
The image presents a design patent for a portable light beacon. The beacon is depicted in two views: a front view and a side view. The overall shape of the beacon is oval with a slightly tapered front end, suggesting a streamlined design for ease of handling. The structure of the beacon is composed of a central cylindrical body with a series of ridges that run vertically along its length, providing a textured surface that may enhance grip. The front end of the beacon features a protruding lens, which is likely the light-emitting component, and a series of buttons or controls, possibly for adjusting the light's brightness or mode. The side view reveals a curved, ergonomic handle that extends from the top of the beacon, designed for comfortable carrying. The proportions of the beacon are balanced, with the cylindrical body and handle appearing to be of equal length, and the lens and controls positioned symmetrically on the front. The image does not provide information about the color or material of the beacon, but the monochromatic line drawing suggests a minimalist aesthetic.
The image presents a design patent drawing of a water shoe. The shoe is depicted in a side view, showcasing its overall shape and structure. It features a large, elongated toe area that tapers towards the back, giving it a pointed appearance. The midsole of the shoe is thick and appears to be designed for buoyancy, with a textured surface that suggests grip and traction. The outsole is not visible in the image, but the midsole's thickness implies a substantial sole for stability. The upper part of the shoe is characterized by a strap that wraps around the wearer's ankle, secured with a buckle. The strap is adjustable, allowing for a snug fit. The shoe's design includes a prominent eyelet for the shoe lace, which is not visible in the image. The overall shape of the shoe is streamlined, with a pointed nose that is likely intended to reduce water resistance. The design is simple yet functional, with a clear emphasis on comfort and performance in water-based activities.

## Check Empty

In [ ]:
def is_missing_or_empty(x):
    if x is None:
        return True
    
    if isinstance(x, float) and pd.isna(x):
        return True
    
    if isinstance(x, list) and len(x) == 0:
        return True
    
    if isinstance(x, np.ndarray) and len(x) == 0:
        return True
    
    if isinstance(x, str) and x.strip() == "[]":
        return True
    
    return False

In [9]:
empty_qwen_rows = df_A[df_A["Qwen"].apply(is_missing_or_empty)]

len(empty_qwen_rows)

0

In [10]:
empty_qwen_rows.head()

Empty DataFrame
Columns: [title, file_names, Loc_class, main_class, sub_class, llava_output, components, Qwen]
Index: []

In [11]:
empty_qwen_rows = df_B[df_B["Qwen"].apply(is_missing_or_empty)]

len(empty_qwen_rows)

0

In [12]:
empty_qwen_rows.head()

Empty DataFrame
Columns: [title, file_names, Loc_class, main_class, sub_class, llava_output, components, Qwen]
Index: []